/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function inferFromBuffer(bytes: Buffer): Promise<string>

export declare function inferFromPath(path: string): Promise<string | null>

export declare function matchBuffer(mimeType: string, bytes: Buffer): Promise<boolean>

export declare function matchPath(mimeType: string, path: string): Promise<boolean>
